### ISSUE TITLE
"go build -o shonkr main.go controller.go texture.go" I don't see a texture.go?

### ISSUE THREAD

**Issue by MostHated** [donomii/shonkr#1]
Hello,
   The instructions say to run "go build -o shonkr main.go controller.go texture.go", but I don't see a texture.go?

Thanks,
-MH

**Comment by donomii** [comment]
Thank you for pointing that out.  The README was out of date, so I fixed it.

Please be aware that this is an ongoing experimental project, so it won't be useful to you as a text editor (yet).

**Comment by MostHated** [comment]
No worries, that is not actually why I was interested in it in the first place, as I too am experimenting. I have been trying out nucular, nuklear, fyne, wails, etc to try and see what ends up being the best fit for what I am wanting to create, so I have just been perusing github for projects to see what kind of stuff other people have been able to create with each of them, and different ways they went about it. I find I typically end up spending way more time researching new and better ways to do things than I do actually creating them, but I enjoy it, lol.

Thanks, 
-MH

**Comment by donomii** [comment]
I've been doing similar.  If you want to get the old version of shonkr
working, you can compile it by typing "go build github.com/donomii/shonkr".
It uses the exp/shiny framework.  I moved away from that because they broke
mouse events, so it stopped working properly on desktop, and I didn't want
to maintain my own branch.

So I ended up with this design that lets me quickly switch to any rendering
engine, which is kind of nice, I guess.

Good luck on your search!
